### ISSUE TITLE
Sortering van validator namen niet alfabetisch / op tijd

### ISSUE THREAD

**Issue by adbgnm** [Geonovum/etf-test-projects-nl#19]
Het is niet duidelijk hoe de volgorde van de validators wordt bepaald. Het is niet alfabetisch maar lijkt iets te maken hebben met het tijdstip van laatste wijziging van een map of bestand. De validators voor StUF-Geo IMGeo worden nu in willekeurige volgorde weergegeven, bijvoorbeeld:

StUF-Geo IMGeo 1.2 BGT
StUF-Geo IMGeo 1.3 Geo-BOR
StUF-Geo IMGeo 1.1.1 BGT

Gevraagd oplossing: de validators alfabetisch op naam sorteren.

**Comment by thijsbrentjens** [comment]
Klopt, het lijkt redelijk willekeurig. De sortering vindt momenteel plaats op de Testdomeinen (bijv "GML" , "INSPIRE", "StUF-Geo IMGeo"), maar niet binnen zo'n Testdomein. Ik zal kijken of dat eenvoudig aan te passen is.

**Comment by thijsbrentjens** [comment]
Dit was een relatief kleine aanpassing, ik heb het gelijk maar doorgevoerd op productie.
