### ISSUE TITLE
srsName mag (ten onrechte?) alleen URL zijn 

### ISSUE THREAD

**Issue by adbgnm** [Geonovum/etf-test-projects-nl#28]
De validator keurt een geometrie waarin in de srsName niet een openGIS url (http://www.opengis.net/def/crs/EPSG/0/28992) is opgenomen af. De vraag is of dit terecht is t.o.v. GML specificaties, immers ook komt voor: urn:ogc:def:crs:EPSG::28992  of EPSG:28992.

_Situatie:_
De volgende geometrie wordt gevalideerd:

<gml:posList srsDimension="2" srsName="**urn:ogc:def:crs:EPSG::28992**">

_Melding validator:_

Requirement IMGeo#Other.Geometry.01
--
Short description | ...
Name | CRS is RD (EPSG:28992)
Reference | n/a

Features with errors: 1.

 File 'voorbeeldbericht_aanvullenden_elementen_wgd': 1 feature(s) with errors:
 object '(no ID)': CRS urn:ogc:def:crs:EPSG::28992 is not .

**Comment by thijsbrentjens** [comment]
In de broncode https://github.com/Geonovum/etf-test-projects-nl/blob/master/src/data/StUF-Geo%20IMGeo%20versie%201.3%20Geo-BOR%20(xsd%2Bgeom)/assertions.xml staan meerdere notaties als geldig:

```
let $featuresWithErrors := $features[//@srsName[.!='http://www.opengis.net/def/crs/EPSG/0/28992' and .!='EPSG:28992' and .!='urn:ogc:def:crs:EPSG::28992']][position() le $limitErrors]
```
Maar dit lijkt niet aanwezig te zijn in de meest recente versie (dd mei 2017) op de productie server.

**Comment by thijsbrentjens** [comment]
De templates bevatten alleen de URI notatie met slashes. Deze moeten ook bijgewerkt worden.

**Comment by thijsbrentjens** [comment]
Overigens, de notaties lijken wel allemaal geldig, ik zie niet zo snel een restrictie obv GML Simple Features.
